config/routes.rb
Theoverheards::Application.routes.draw do
  resources :quotes, :only => [:index, :new, :create]
  root :to => "quotes#index"

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :content

  validates :content, :length   => { :minimum => 3 },
                      :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.order("created_at DESC").all
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.create params[:quote]

    if @quote.save
      redirect_to root_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title The OHs
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .container
      .row
        #content{:class => [ 'span12', 'offset3']}
          %div{:class => 'span10'}
            .row
              %div{:class => ['title', 'span6']}
                The OHs
          = yield

app/views/quotes/_quote.html.haml
.row
  %div{:id => "quote_#{quote.id}", :class => ['quote', 'span10']}
    = quote.content
    %p
      %small #{quote.created_at}

app/views/quotes/index.html.haml
.row
  %div{:class => ['add_quote', 'span2', 'offset8']}
    = link_to 'Add a new one', new_quote_path
- @quotes.each do |quote|
  = render :partial => "quote", :object => quote
  %br

app/views/quotes/new.html.haml
%div{:class => ['quote_form', 'span10']}
  = form_for @quote, :html => { :class => 'form-stacked' } do |f|
    - if @quote.errors.any?
      %div{:class => ['alert-message', 'block-message', 'error']}
        %p
          Whoops, that won't work.  Probably because:
        %br
        %ul
          - @quote.errors.full_messages.each do |message|
            %li
              = message
        %br
        %p
          Try to change it and try again
    %fieldset
      %legend Quote:
      %div{:class => 'clearfix'}
        %div{:class => ['input', 'xlarge']}
          = f.text_area :content, :rows => 10, :class => 'xxlarge'
      = f.submit 'Add', :class => 'btn large'